CategorySize.create(size_id: 1, category_id: 3)
CategorySize.create(size_id: 1, category_id: 4)
CategorySize.create(size_id: 1, category_id: 5)
CategorySize.create(size_id: 1, category_id: 6)
CategorySize.create(size_id: 1, category_id: 7)
CategorySize.create(size_id: 1, category_id: 8)
CategorySize.create(size_id: 1, category_id: 9)
CategorySize.create(size_id: 1, category_id: 10)
CategorySize.create(size_id: 1, category_id: 11)
CategorySize.create(size_id: 1, category_id: 12)
CategorySize.create(size_id: 1, category_id: 13)
CategorySize.create(size_id: 1, category_id: 14)
CategorySize.create(size_id: 1, category_id: 15)
CategorySize.create(size_id: 1, category_id: 16)
CategorySize.create(size_id: 1, category_id: 17)
CategorySize.create(size_id: 1, category_id: 18)
CategorySize.create(size_id: 1, category_id: 19)

CategorySize.create(size_id: 1, category_id: 21)
CategorySize.create(size_id: 1, category_id: 22)
CategorySize.create(size_id: 1, category_id: 23)
CategorySize.create(size_id: 1, category_id: 24)
CategorySize.create(size_id: 1, category_id: 25)
CategorySize.create(size_id: 1, category_id: 26)
CategorySize.create(size_id: 1, category_id: 27)
CategorySize.create(size_id: 1, category_id: 28)
CategorySize.create(size_id: 1, category_id: 29)
CategorySize.create(size_id: 1, category_id: 30)
CategorySize.create(size_id: 1, category_id: 31)
CategorySize.create(size_id: 1, category_id: 32)
CategorySize.create(size_id: 1, category_id: 33)
CategorySize.create(size_id: 1, category_id: 34)
CategorySize.create(size_id: 1, category_id: 35)
CategorySize.create(size_id: 1, category_id: 36)
CategorySize.create(size_id: 1, category_id: 37)
CategorySize.create(size_id: 1, category_id: 38)
CategorySize.create(size_id: 1, category_id: 39)
CategorySize.create(size_id: 1, category_id: 40)
CategorySize.create(size_id: 1, category_id: 41)

CategorySize.create(size_id: 1, category_id: 44)
CategorySize.create(size_id: 1, category_id: 45)
CategorySize.create(size_id: 1, category_id: 46)
CategorySize.create(size_id: 1, category_id: 47)
CategorySize.create(size_id: 1, category_id: 48)
CategorySize.create(size_id: 1, category_id: 49)
CategorySize.create(size_id: 1, category_id: 50)
CategorySize.create(size_id: 1, category_id: 51)
CategorySize.create(size_id: 1, category_id: 52)
CategorySize.create(size_id: 1, category_id: 53)
CategorySize.create(size_id: 1, category_id: 54)

CategorySize.create(size_id: 1, category_id: 57)
CategorySize.create(size_id: 1, category_id: 58)
CategorySize.create(size_id: 1, category_id: 59)
CategorySize.create(size_id: 1, category_id: 60)

CategorySize.create(size_id: 1, category_id: 63)
CategorySize.create(size_id: 1, category_id: 64)
CategorySize.create(size_id: 1, category_id: 65)

CategorySize.create(size_id: 12, category_id: 68)
CategorySize.create(size_id: 12, category_id: 69)
CategorySize.create(size_id: 12, category_id: 70)
CategorySize.create(size_id: 12, category_id: 71)
CategorySize.create(size_id: 12, category_id: 72)
CategorySize.create(size_id: 12, category_id: 73)
CategorySize.create(size_id: 12, category_id: 74)
CategorySize.create(size_id: 12, category_id: 75)
CategorySize.create(size_id: 12, category_id: 76)

CategorySize.create(size_id: 1, category_id: 79)
CategorySize.create(size_id: 1, category_id: 80)

CategorySize.create(size_id: 1, category_id: 174)
CategorySize.create(size_id: 1, category_id: 175)
CategorySize.create(size_id: 1, category_id: 176)

CategorySize.create(size_id: 1, category_id: 179)
CategorySize.create(size_id: 1, category_id: 180)
CategorySize.create(size_id: 1, category_id: 181)

CategorySize.create(size_id: 1, category_id: 187)
CategorySize.create(size_id: 1, category_id: 188)
CategorySize.create(size_id: 1, category_id: 189)
CategorySize.create(size_id: 1, category_id: 190)
CategorySize.create(size_id: 1, category_id: 191)
CategorySize.create(size_id: 1, category_id: 192)
CategorySize.create(size_id: 1, category_id: 193)
CategorySize.create(size_id: 1, category_id: 194)

CategorySize.create(size_id: 1, category_id: 202)
CategorySize.create(size_id: 1, category_id: 203)
CategorySize.create(size_id: 1, category_id: 204)
CategorySize.create(size_id: 1, category_id: 205)
CategorySize.create(size_id: 1, category_id: 206)
CategorySize.create(size_id: 1, category_id: 207)
CategorySize.create(size_id: 1, category_id: 208)
CategorySize.create(size_id: 1, category_id: 209)
CategorySize.create(size_id: 1, category_id: 210)
CategorySize.create(size_id: 1, category_id: 211)
CategorySize.create(size_id: 1, category_id: 212)

CategorySize.create(size_id: 1, category_id: 215)
CategorySize.create(size_id: 1, category_id: 216)
CategorySize.create(size_id: 1, category_id: 217)
CategorySize.create(size_id: 1, category_id: 218)
CategorySize.create(size_id: 1, category_id: 219)
CategorySize.create(size_id: 1, category_id: 220)
CategorySize.create(size_id: 1, category_id: 221)
CategorySize.create(size_id: 1, category_id: 222)
CategorySize.create(size_id: 1, category_id: 223)
CategorySize.create(size_id: 1, category_id: 224)
CategorySize.create(size_id: 1, category_id: 225)
CategorySize.create(size_id: 1, category_id: 226)
CategorySize.create(size_id: 1, category_id: 227)
CategorySize.create(size_id: 1, category_id: 228)
CategorySize.create(size_id: 1, category_id: 229)
CategorySize.create(size_id: 1, category_id: 230)
CategorySize.create(size_id: 1, category_id: 231)
CategorySize.create(size_id: 1, category_id: 232)
CategorySize.create(size_id: 1, category_id: 233)
CategorySize.create(size_id: 1, category_id: 234)
CategorySize.create(size_id: 1, category_id: 235)
CategorySize.create(size_id: 1, category_id: 236)

CategorySize.create(size_id: 1, category_id: 239)
CategorySize.create(size_id: 1, category_id: 240)
CategorySize.create(size_id: 1, category_id: 241)
CategorySize.create(size_id: 1, category_id: 242)
CategorySize.create(size_id: 1, category_id: 243)
CategorySize.create(size_id: 1, category_id: 244)
CategorySize.create(size_id: 1, category_id: 245)
CategorySize.create(size_id: 1, category_id: 246)

CategorySize.create(size_id: 12, category_id: 246)
CategorySize.create(size_id: 12, category_id: 247)
CategorySize.create(size_id: 12, category_id: 248)
CategorySize.create(size_id: 12, category_id: 249)
CategorySize.create(size_id: 12, category_id: 250)
CategorySize.create(size_id: 12, category_id: 251)
CategorySize.create(size_id: 12, category_id: 252)
CategorySize.create(size_id: 12, category_id: 253)
CategorySize.create(size_id: 12, category_id: 254)
CategorySize.create(size_id: 12, category_id: 255)

CategorySize.create(size_id: 1, category_id: 271)
CategorySize.create(size_id: 1, category_id: 272)
CategorySize.create(size_id: 1, category_id: 273)
CategorySize.create(size_id: 1, category_id: 274)

CategorySize.create(size_id: 1, category_id: 331)
CategorySize.create(size_id: 1, category_id: 332)

CategorySize.create(size_id: 1, category_id: 341)
CategorySize.create(size_id: 1, category_id: 342)

CategorySize.create(size_id: 29, category_id: 348)
CategorySize.create(size_id: 29, category_id: 349)
CategorySize.create(size_id: 29, category_id: 350)
CategorySize.create(size_id: 29, category_id: 351)
CategorySize.create(size_id: 29, category_id: 352)
CategorySize.create(size_id: 29, category_id: 353)
CategorySize.create(size_id: 29, category_id: 354)
CategorySize.create(size_id: 29, category_id: 355)
CategorySize.create(size_id: 29, category_id: 356)
CategorySize.create(size_id: 29, category_id: 357)
CategorySize.create(size_id: 29, category_id: 358)

CategorySize.create(size_id: 29, category_id: 360)
CategorySize.create(size_id: 29, category_id: 361)
CategorySize.create(size_id: 29, category_id: 362)
CategorySize.create(size_id: 29, category_id: 363)
CategorySize.create(size_id: 29, category_id: 364)
CategorySize.create(size_id: 29, category_id: 365)
CategorySize.create(size_id: 29, category_id: 366)
CategorySize.create(size_id: 29, category_id: 367)

CategorySize.create(size_id: 29, category_id: 369)
CategorySize.create(size_id: 29, category_id: 370)
CategorySize.create(size_id: 29, category_id: 371)
CategorySize.create(size_id: 29, category_id: 372)
CategorySize.create(size_id: 29, category_id: 373)
CategorySize.create(size_id: 29, category_id: 374)
CategorySize.create(size_id: 29, category_id: 375)
CategorySize.create(size_id: 29, category_id: 376)

CategorySize.create(size_id: 35, category_id: 378)
CategorySize.create(size_id: 35, category_id: 379)
CategorySize.create(size_id: 35, category_id: 380)
CategorySize.create(size_id: 35, category_id: 381)
CategorySize.create(size_id: 35, category_id: 382)
CategorySize.create(size_id: 35, category_id: 383)
CategorySize.create(size_id: 35, category_id: 384)
CategorySize.create(size_id: 35, category_id: 385)
CategorySize.create(size_id: 35, category_id: 386)
CategorySize.create(size_id: 35, category_id: 387)
CategorySize.create(size_id: 35, category_id: 388)
CategorySize.create(size_id: 35, category_id: 389)
CategorySize.create(size_id: 35, category_id: 390)
CategorySize.create(size_id: 35, category_id: 391)
CategorySize.create(size_id: 35, category_id: 392)
CategorySize.create(size_id: 35, category_id: 393)
CategorySize.create(size_id: 35, category_id: 394)
CategorySize.create(size_id: 35, category_id: 395)

CategorySize.create(size_id: 35, category_id: 397)
CategorySize.create(size_id: 35, category_id: 398)
CategorySize.create(size_id: 35, category_id: 399)
CategorySize.create(size_id: 35, category_id: 400)
CategorySize.create(size_id: 35, category_id: 401)
CategorySize.create(size_id: 35, category_id: 402)
CategorySize.create(size_id: 35, category_id: 403)
CategorySize.create(size_id: 35, category_id: 404)
CategorySize.create(size_id: 35, category_id: 405)
CategorySize.create(size_id: 35, category_id: 406)
CategorySize.create(size_id: 35, category_id: 407)
CategorySize.create(size_id: 35, category_id: 408)
CategorySize.create(size_id: 35, category_id: 409)
CategorySize.create(size_id: 35, category_id: 410)

CategorySize.create(size_id: 35, category_id: 412)
CategorySize.create(size_id: 35, category_id: 413)
CategorySize.create(size_id: 35, category_id: 414)
CategorySize.create(size_id: 35, category_id: 415)
CategorySize.create(size_id: 35, category_id: 416)
CategorySize.create(size_id: 35, category_id: 417)
CategorySize.create(size_id: 35, category_id: 418)
CategorySize.create(size_id: 35, category_id: 419)

CategorySize.create(size_id: 43, category_id: 421)
CategorySize.create(size_id: 43, category_id: 422)
CategorySize.create(size_id: 43, category_id: 423)
CategorySize.create(size_id: 43, category_id: 424)
CategorySize.create(size_id: 43, category_id: 425)

CategorySize.create(size_id: 52, category_id: 926)
CategorySize.create(size_id: 52, category_id: 927)

CategorySize.create(size_id: 65, category_id: 932)

CategorySize.create(size_id: 76, category_id: 1045)

CategorySize.create(size_id: 84, category_id: 1047)

CategorySize.create(size_id: 12, category_id: 1048)

CategorySize.create(size_id: 43, category_id: 1049)

CategorySize.create(size_id: 1, category_id: 1050)
CategorySize.create(size_id: 1, category_id: 1051)

CategorySize.create(size_id: 35, category_id: 1052)

CategorySize.create(size_id: 101, category_id: 1057)

CategorySize.create(size_id: 84, category_id: 1058)

CategorySize.create(size_id: 12, category_id: 1059)

CategorySize.create(size_id: 43, category_id: 1060)

CategorySize.create(size_id: 1, category_id: 1062)
CategorySize.create(size_id: 1, category_id: 1063)

CategorySize.create(size_id: 35, category_id: 1064)

CategorySize.create(size_id: 109, category_id: 1212)
CategorySize.create(size_id: 109, category_id: 1213)
CategorySize.create(size_id: 109, category_id: 1214)
CategorySize.create(size_id: 109, category_id: 1215)

CategorySize.create(size_id: 123, category_id: 1244)

CategorySize.create(size_id: 130, category_id: 1264)