#服のサイズ
clothes = Size.create(size: "洋服のサイズ")
clothes_1 = clothes.children.create(size: "XXS以下")
clothes_2 = clothes.children.create(size: "XS(SS)")
clothes_3 = clothes.children.create(size: "S")
clothes_4 = clothes.children.create(size: "M")
clothes_5 = clothes.children.create(size: "L")
clothes_6 = clothes.children.create(size: "XL(LL)")
clothes_7 = clothes.children.create(size: "2XL(3L)")
clothes_8 = clothes.children.create(size: "3XL(4L)")
clothes_9 = clothes.children.create(size: "4XL(5L)以上")
clothes_1 = clothes.children.create(size: "FREE SIZE")

# 靴のサイズ
shose = Size.create(size: "靴のサイズ")
shose_1 = shose.children.create(size: "20cm以下")
shose_2 = shose.children.create(size: "20.5cm")
shose_3 = shose.children.create(size: "21cm")
shose_4 = shose.children.create(size: "21.5cm")
shose_5 = shose.children.create(size: "22cm")
shose_6 = shose.children.create(size: "22.5cm")
shose_7 = shose.children.create(size: "23cm")
shose_8 = shose.children.create(size: "23.5cm")
shose_9 = shose.children.create(size: "24cm")
shose_10 = shose.children.create(size: "24.5cm")
shose_11 = shose.children.create(size: "25cm")
shose_12 = shose.children.create(size: "25.5cm")
shose_13 = shose.children.create(size: "26cm")
shose_14 = shose.children.create(size: "26.5cm")
shose_15 = shose.children.create(size: "27cm")
shose_16 = shose.children.create(size: "27.5cm以上")