#服のサイズ
clothes = Size.create(size: "洋服のサイズ")
clothes_1 = clothes.children.create(size: "XXS以下")
clothes_2 = clothes.children.create(size: "XS(SS)")
clothes_3 = clothes.children.create(size: "S")
clothes_4 = clothes.children.create(size: "M")
clothes_5 = clothes.children.create(size: "L")
clothes_6 = clothes.children.create(size: "XL(LL)")
clothes_7 = clothes.children.create(size: "2XL(3L)")
clothes_8 = clothes.children.create(size: "3XL(4L)")
clothes_9 = clothes.children.create(size: "4XL(5L)以上")
clothes_1 = clothes.children.create(size: "FREE SIZE")

# 靴のサイズ
shose = Size.create(size: "靴のサイズ")
shose_1 = shose.children.create(size: "20cm以下")
shose_2 = shose.children.create(size: "20.5cm")
shose_3 = shose.children.create(size: "21cm")
shose_4 = shose.children.create(size: "21.5cm")
shose_5 = shose.children.create(size: "22cm")
shose_6 = shose.children.create(size: "22.5cm")
shose_7 = shose.children.create(size: "23cm")
shose_8 = shose.children.create(size: "23.5cm")
shose_9 = shose.children.create(size: "24cm")
shose_10 = shose.children.create(size: "24.5cm")
shose_11 = shose.children.create(size: "25cm")
shose_12 = shose.children.create(size: "25.5cm")
shose_13 = shose.children.create(size: "26cm")
shose_14 = shose.children.create(size: "26.5cm")
shose_15 = shose.children.create(size: "27cm")
shose_16 = shose.children.create(size: "27.5cm以上")

#子供服のサイズ~95cm
baby_clothes = Size.create(size: "子供服のサイズ")
baby_clothes_1 = baby_clothes.children.create(size: "60cm")
baby_clothes_2 = baby_clothes.children.create(size: "70cm")
baby_clothes_3 = baby_clothes.children.create(size: "80cm")
baby_clothes_4 = baby_clothes.children.create(size: "90cm")
baby_clothes_5 = baby_clothes.children.create(size: "95cm")

#子供服のサイズ100cm~
child_clothes = Size.create(size: "子供服のサイズ")
child_clothes_1 = child_clothes.children.create(size: "100cm")
child_clothes_2 = child_clothes.children.create(size: "110cm")
child_clothes_3 = child_clothes.children.create(size: "120cm")
child_clothes_4 = child_clothes.children.create(size: "130cm")
child_clothes_5 = child_clothes.children.create(size: "140cm")
child_clothes_6 = child_clothes.children.create(size: "150cm")
child_clothes_7 = child_clothes.children.create(size: "160cm")

#子供靴
baby_shose = Size.create(size: "子供靴")
baby_shose_1 = baby_shose.children.create(size: "10.5cm以下")
baby_shose_2 = baby_shose.children.create(size: "11cm・11.5cm")
baby_shose_3 = baby_shose.children.create(size: "12cm・12.5cm")
baby_shose_4 = baby_shose.children.create(size: "13cm・13.5cm")
baby_shose_5 = baby_shose.children.create(size: "14cm・14.5cm")
baby_shose_6 = baby_shose.children.create(size: "15cm・15.5cm")
baby_shose_7 = baby_shose.children.create(size: "16cm・16.5cm")
baby_shose_8 = baby_shose.children.create(size: "17cm以上")

#カメラレンズサイズ
camera_lens = Size.create(size: "カメラレンズ")
camera_lens_1 = camera_lens.children.create(size: "ニコンFマウント")
camera_lens_2 = camera_lens.children.create(size: "キヤノンEFマウント")
camera_lens_3 = camera_lens.children.create(size: "ペンタックスKマウント")
camera_lens_4 = camera_lens.children.create(size: "ペンタックスQマウント")
camera_lens_5 = camera_lens.children.create(size: "フォーサーズマウント")
camera_lens_6 = camera_lens.children.create(size: "マイクロフォーサーズマウント")
camera_lens_7 = camera_lens.children.create(size: "αAマウント")
camera_lens_8 = camera_lens.children.create(size: "αEマウント")
camera_lens_9 = camera_lens.children.create(size: "ニコン1マウント")
camera_lens_10 = camera_lens.children.create(size: "キヤノンEF-Mマウント")
camera_lens_11 = camera_lens.children.create(size: "Xマウント")
camera_lens_12 = camera_lens.children.create(size: "シグマSAマウント")

#テレビのサイズ
television = Size.create(size: "テレビのサイズ")
television_1 = television.children.create(size: "~20インチ")
television_1 = television.children.create(size: "20~26インチ")
television_1 = television.children.create(size: "26~32インチ")
television_1 = television.children.create(size: "32~37インチ")
television_1 = television.children.create(size: "37~40インチ")
television_1 = television.children.create(size: "40~42インチ")
television_1 = television.children.create(size: "42~46インチ")
television_1 = television.children.create(size: "46~52インチ")
television_1 = television.children.create(size: "52~60インチ")
television_1 = television.children.create(size: "60インチ~")

#ボード板のサイズ
snowboard_board = Size.create(size: "ボード板のサイズ")
snowboard_board_1 = snowboard_board.children.create(size: "135cm~140cm未満")
snowboard_board_2 = snowboard_board.children.create(size: "140cm~145cm未満")
snowboard_board_3 = snowboard_board.children.create(size: "145cm~150cm未満")
snowboard_board_4 = snowboard_board.children.create(size: "150cm~155cm未満")
snowboard_board_5 = snowboard_board.children.create(size: "155cm~160cm未満")
snowboard_board_6 = snowboard_board.children.create(size: "160cm~165cm未満")
snowboard_board_7 = snowboard_board.children.create(size: "165cm~170cm未満")

#メンズボード用ブーツのサイズ
snow_mensboots = Size.create(size: "メンズボード用ブーツのサイズ")
snow_mensboots_1 = snow_mensboots.children.create(size: "23.5cm以下")
snow_mensboots_2 = snow_mensboots.children.create(size: "24cm")
snow_mensboots_3 = snow_mensboots.children.create(size: "24.5cm")
snow_mensboots_4 = snow_mensboots.children.create(size: "25cm")
snow_mensboots_5 = snow_mensboots.children.create(size: "25.5cm")
snow_mensboots_6 = snow_mensboots.children.create(size: "26cm")
snow_mensboots_7 = snow_mensboots.children.create(size: "26.5cm")
snow_mensboots_8 = snow_mensboots.children.create(size: "27cm")
snow_mensboots_9 = snow_mensboots.children.create(size: "27.5cm")
snow_mensboots_10 = snow_mensboots.children.create(size: "28cm")
snow_mensboots_11 = snow_mensboots.children.create(size: "28.5cm")
snow_mensboots_12 = snow_mensboots.children.create(size: "29cm")
snow_mensboots_13 = snow_mensboots.children.create(size: "29.5cm")
snow_mensboots_14 = snow_mensboots.children.create(size: "30cm")
snow_mensboots_15 = snow_mensboots.children.create(size: "30.5cm")
snow_mensboots_16 = snow_mensboots.children.create(size: "31cm以上")

#スキー板のサイズ
ski_board = Size.create(size: "スキー板のサイズ")
ski_board_1 = ski_board.children.create(size: "140cm~")
ski_board_2 = ski_board.children.create(size: "150cm~")
ski_board_3 = ski_board.children.create(size: "160cm~")
ski_board_4 = ski_board.children.create(size: "170cm~")
ski_board_5 = ski_board.children.create(size: "スキーボード")
ski_board_6 = ski_board.children.create(size: "子供用")
ski_board_7 = ski_board.children.create(size: "その他")

#タイヤのサイズ
tire = Size.create(size: "タイヤのサイズ")
tire_1 = tire.children.create(size: "12インチ")
tire_2 = tire.children.create(size: "13インチ")
tire_3 = tire.children.create(size: "14インチ")
tire_4 = tire.children.create(size: "15インチ")
tire_5 = tire.children.create(size: "16インチ")
tire_6 = tire.children.create(size: "17インチ")
tire_7 = tire.children.create(size: "18インチ")
tire_8 = tire.children.create(size: "19インチ")
tire_9 = tire.children.create(size: "20インチ")
tire_10 = tire.children.create(size: "21インチ")
tire_11 = tire.children.create(size: "22インチ")
tire_12 = tire.children.create(size: "23インチ")
tire_13 = tire.children.create(size: "24インチ")

#オートバイのサイズ
bike = Size.create(size: "オートのサイズ")
bike_1 = bike.children.create(size: "50cc以下")
bike_2 = bike.children.create(size: "51cc~125cc")
bike_3 = bike.children.create(size: "126cc~250cc")
bike_4 = bike.children.create(size: "251cc~400cc")
bike_5 = bike.children.create(size: "401cc~750cc")
bike_6 = bike.children.create(size: "751cc以上")

#ヘルメットのサイズ
helmet = Size.create(size: "ヘルメットのサイズ")
helmet_1 = helmet.children.create(size: "XSサイズ以下")
helmet_2 = helmet.children.create(size: "Sサイズ")
helmet_3 = helmet.children.create(size: "Mサイズ")
helmet_4 = helmet.children.create(size: "Lサイズ")
helmet_5 = helmet.children.create(size: "XLサイズ")
helmet_6 = helmet.children.create(size: "XXLサイズ")
helmet_7 = helmet.children.create(size: "XXLサイズ以上")
helmet_8 = helmet.children.create(size: "子ども用")


