#服のサイズ
clothes = Size.create(size: "洋服のサイズ")
clothes_1 = clothes.children.create(size: "XXS以下")
clothes_2 = clothes.children.create(size: "XS(SS)")
clothes_3 = clothes.children.create(size: "S")
clothes_4 = clothes.children.create(size: "M")
clothes_5 = clothes.children.create(size: "L")
clothes_6 = clothes.children.create(size: "XL(LL)")
clothes_7 = clothes.children.create(size: "2XL(3L)")
clothes_8 = clothes.children.create(size: "3XL(4L)")
clothes_9 = clothes.children.create(size: "4XL(5L)以上")
clothes_1 = clothes.children.create(size: "FREE SIZE")

# 靴のサイズ
shose = Size.create(size: "靴のサイズ")
shose_1 = shose.children.create(size: "20cm以下")
shose_2 = shose.children.create(size: "20.5cm")
shose_3 = shose.children.create(size: "21cm")
shose_4 = shose.children.create(size: "21.5cm")
shose_5 = shose.children.create(size: "22cm")
shose_6 = shose.children.create(size: "22.5cm")
shose_7 = shose.children.create(size: "23cm")
shose_8 = shose.children.create(size: "23.5cm")
shose_9 = shose.children.create(size: "24cm")
shose_10 = shose.children.create(size: "24.5cm")
shose_11 = shose.children.create(size: "25cm")
shose_12 = shose.children.create(size: "25.5cm")
shose_13 = shose.children.create(size: "26cm")
shose_14 = shose.children.create(size: "26.5cm")
shose_15 = shose.children.create(size: "27cm")
shose_16 = shose.children.create(size: "27.5cm以上")

#子供服のサイズ〜95cm
baby_clothes = Size.create(size: "子供服のサイズ")
baby_clothes_1 = baby_clothes.children.create(size: "60cm")
baby_clothes_2 = baby_clothes.children.create(size: "70cm")
baby_clothes_3 = baby_clothes.children.create(size: "80cm")
baby_clothes_4 = baby_clothes.children.create(size: "90cm")
baby_clothes_5 = baby_clothes.children.create(size: "95cm")

#子供服のサイズ100cm〜
child_clothes = Size.create(size: "子供服のサイズ")
child_clothes_1 = child_clothes.children.create(size: "100cm")
child_clothes_2 = child_clothes.children.create(size: "110cm")
child_clothes_3 = child_clothes.children.create(size: "120cm")
child_clothes_4 = child_clothes.children.create(size: "130cm")
child_clothes_5 = child_clothes.children.create(size: "140cm")
child_clothes_6 = child_clothes.children.create(size: "150cm")
child_clothes_7 = child_clothes.children.create(size: "160cm")

#子供靴
baby_shose = Size.create(size: "子供靴")
baby_shose_1 = baby_shose.children.create(size: "10.5cm以下")
baby_shose_2 = baby_shose.children.create(size: "11cm・11.5cm")
baby_shose_3 = baby_shose.children.create(size: "12cm・12.5cm")
baby_shose_4 = baby_shose.children.create(size: "13cm・13.5cm")
baby_shose_5 = baby_shose.children.create(size: "14cm・14.5cm")
baby_shose_6 = baby_shose.children.create(size: "15cm・15.5cm")
baby_shose_7 = baby_shose.children.create(size: "16cm・16.5cm")
baby_shose_8 = baby_shose.children.create(size: "17cm以上")

